### ISSUE TITLE
Symbol list inconsistent parsing

### ISSUE THREAD

**Issue by cmccarthy1** [KxSystems/docs#28]
* There appears to a parsing error with the new use of `<pre><code class="language-q">` in the definition of code blocks over the previous use of triple back tick q as a code block start.

* In particular the definition of code containing ` as a character for the definition of a symbol list or in embedPy for accessing python objects is not being parsed in accordance with expected behaviour for q

The code blocks in this section show this incorrect parsing (this is the only instance observed so far)

https://code.kx.com/q/ml/automl/faq/#keras-models

Namely the definition of `i.keraslist` should be a list of symbols, and the definition of `layer1_nm` in customregkeras should also be a symbol list.

**Comment by ghost** [comment]
The use of `pre` and `code` elements is for nesting code blocks inside e.g. definition lists of admonitions – a step too far for Markdown. I do not know why but certain characters inside the code elements then need escaping:
```
`\$
```
Possibly also `*`, can’t recall offhand. Sorry about the inconvenience. As you will have seen, I do everything I can to keep the Markdown source human-readable, and this does not help.
