### ISSUE TITLE
Bad link on java whitepaper

### ISSUE THREAD

**Issue by sshanks-kx** [KxSystems/docs#35]
Ref: https://code.kx.com/q/wp/java-api/

This line 

> The API is contained in a  single source file on GitHub. 

is referencing code thats moved, so the link is broken.
Prob better if it just linked to the repo on github  (https://github.com/KxSystems/javakdb) so that they can see details of the API/etc when visiting rather than bypassing it, and also allowing code to be refactored further.

**Comment by ghost** [comment]
Fixed in commit 2d35883. Tx for the catch.
