### ISSUE TITLE
Change location of c.cs that is referenced in docs

### ISSUE THREAD

**Issue by sshanks-kx** [KxSystems/docs#39]
New location of C# API is https://github.com/KxSystems/csharpkdb

This doc https://code.kx.com/q/interfaces/csharp-client-for-q/ currently points to https://github.com/KxSystems/kdb/blob/master/c/c.cs in the first sentance. Should be changed to https://github.com/KxSystems/csharpkdb

Thanks

**Comment by ghost** [comment]
Fixed – thanks for catch.
