### ISSUE TITLE
Undocumented asc behavior 

### ISSUE THREAD

**Issue by davidcrossey** [KxSystems/docs#76]
As per [Behavior of asc table](https://community.kx.com/t5/kdb-and-q/Behavior-of-asc-table/m-p/12803/emcs_t/S2h8ZW1haWx8Ym9hcmRfc3Vic2NyaXB0aW9ufEw1NldMQlBJOE1XN1pVfDEyODAzfFNVQlNDUklQVElPTlN8aEs#M78) there appears to be undocumented functionality of asc on a table with a single key and single column:
>But when there is only one non-keyed column, it's actually the sorted attribute that is set.
```
q)meta asc ([c1:`a`b] c2:2 1)
c | t f a
--| -----
c1| s 
c2| j   s
q)meta asc ([c1:`a`b] c2:2 1; c3:01b)
c | t f a
--| -----
c1| s
c2| j   p
c3| b
```

Documentation to be updated: https://code.kx.com/q/ref/asc/#asc
Duplicate information:  https://code.kx.com/q/ref/set-attribute/#sorted

FYI: @StephenTaylor-Kx, CC: @rianoc

**Comment by ghost** [comment]
Closed by commit a9a3a82a11a3f9c9623bb7d200c9547f00595ef2
