### ISSUE TITLE
pub sub from kdb to pyq

### ISSUE THREAD

**Issue by ashgen** [KxSystems/docs#87]
Hi team, I need to pub sub using pyq from kdb . Can you please let me know an example of how it can be done . Can't find any example on web or otherwise

**Comment by bakx** [comment]
Please direct your question to https://community.kx.com/t5/kdb-and-q/bd-p/kdb-q-questions  and someone from KX or a community member will likely give you the code sample you requested.

**Comment by ghost** [comment]
Tx, Gideon – as you say, not an issue for this repo.
